const TIPO_CATEGORIA = {
  Apartamento: 'residencial',
  Casa: 'residencial',
  Sobrado: 'residencial',
  'Galpão/Barracão': 'comercial-industrial',
  'Sala/Salão': 'comercial-industrial',
  Negócio: 'comercial-industrial',
  Prédio: 'comercial-industrial',
  Garagem: 'comercial-industrial',
  Terreno: 'terrenos',
  Chácara: 'rural',
  Sítio: 'rural',
  Fazenda: 'rural',
};

function buildTitulo(imovel) {
  if (imovel.condominio) {
    return `${imovel.tipo} - ${imovel.condominio}`;
  }
  if (imovel.bairro) {
    return `${imovel.tipo} em ${imovel.bairro}`;
  }
  return `${imovel.tipo} em ${imovel.cidade}`;
}

exports.seed = async function (knex) {
  await knex('imovel_fotos').del();
  await knex('imoveis').del();

  const categorias = await knex('categorias').select('id', 'slug');
  const catMap = {};
  for (const c of categorias) catMap[c.slug] = c.id;

  const venda = [
    {
      id: 254039,
      tipo: 'Apartamento',
      preco: null,
      endereco: 'Avenida Horacio Raccanelo Filho, 6326',
      bairro: 'Zona 07',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 168.0,
      quartos: 3,
      banheiros: 5,
      vagas: 2,
      url: 'https://tradicaoimoveismga.com.br/imovel/254039',
    },
    {
      id: 11042,
      tipo: 'Fazenda',
      preco: null,
      endereco: '',
      bairro: '',
      cidade: 'Rio Branco do Ivaí',
      estado: 'PR',
      condominio: null,
      area_m2: null,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11042',
    },
    {
      id: 67397,
      tipo: 'Terreno',
      preco: 75000.0,
      endereco: '',
      bairro: 'Jardim Imperial',
      cidade: 'Paiçandu',
      estado: 'PR',
      condominio: null,
      area_m2: 153.0,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/67397',
    },
    {
      id: 55240,
      tipo: 'Apartamento',
      preco: 180000.0,
      endereco: 'Rua Marianinha, 240',
      bairro: 'Jd. Aeroporto',
      cidade: 'Arapongas',
      estado: 'PR',
      condominio: 'Residencial Arapongas',
      area_m2: 47.0,
      quartos: 2,
      banheiros: 1,
      vagas: 1,
      url: 'https://tradicaoimoveismga.com.br/imovel/55240',
    },
    {
      id: 11068,
      tipo: 'Terreno',
      preco: 370000.0,
      endereco: 'Rua Múcio Leão, 178',
      bairro: 'Vila Esperança',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: null,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11068',
    },
    {
      id: 11058,
      tipo: 'Sala/Salão',
      preco: 380000.0,
      endereco: 'RODOVIA PR 317 KM 06',
      bairro: 'NÃO INFORMADO',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: 'VEST SUL',
      area_m2: 34.0,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11058',
    },
    {
      id: 11211,
      tipo: 'Casa',
      preco: 500000.0,
      endereco: 'Rua Agostinho Franco Da Rocha, 165',
      bairro: 'Cj Porto Seguro II',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 83.0,
      quartos: 3,
      banheiros: 1,
      vagas: 2,
      url: 'https://tradicaoimoveismga.com.br/imovel/11211',
    },
    {
      id: 11057,
      tipo: 'Casa',
      preco: 550000.0,
      endereco: 'RUA MONSENHOR TANAKA, 545',
      bairro: 'VL EMÍLIA',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 97.65,
      quartos: 3,
      banheiros: 2,
      vagas: 2,
      url: 'https://tradicaoimoveismga.com.br/imovel/11057',
    },
    {
      id: 96193,
      tipo: 'Apartamento',
      preco: 600000.0,
      endereco: 'Avenida Doutor Alexandre Rasgulaeff, 3342',
      bairro: 'Parque Residencial Cidade Nova',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 79.27,
      quartos: 3,
      banheiros: 2,
      vagas: 2,
      url: 'https://tradicaoimoveismga.com.br/imovel/96193',
    },
    {
      id: 236356,
      tipo: 'Apartamento',
      preco: 650000.0,
      endereco: 'AV DR ALEXANDRE RASGULAEF, 3342',
      bairro: 'JD CIDADE NOVA',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: 'EDIFICIO IMPERIUM RESIDENCE',
      area_m2: null,
      quartos: 3,
      banheiros: 2,
      vagas: 1,
      url: 'https://tradicaoimoveismga.com.br/imovel/236356',
    },
    {
      id: 11056,
      tipo: 'Sobrado',
      preco: 650000.0,
      endereco: 'Rua Edézio de Almeida Lima, 346',
      bairro: 'Jardim Monte Rei',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: null,
      quartos: 3,
      banheiros: 4,
      vagas: 2,
      url: 'https://tradicaoimoveismga.com.br/imovel/11056',
    },
    {
      id: 11219,
      tipo: 'Apartamento',
      preco: 650000.0,
      endereco: 'Rua Guarita, 320',
      bairro: 'Vila Bosque',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: 'Edifício Ville Vert',
      area_m2: 53.0,
      quartos: 2,
      banheiros: 2,
      vagas: 1,
      url: 'https://tradicaoimoveismga.com.br/imovel/11219',
    },
    {
      id: 73119,
      tipo: 'Galpão/Barracão',
      preco: 800000.0,
      endereco: 'Avenida Deputado José Alves dos Santos, 3133',
      bairro: 'Jardim Brasil',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 144.0,
      quartos: null,
      banheiros: 2,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/73119',
    },
    {
      id: 69948,
      tipo: 'Casa',
      preco: 850000.0,
      endereco: 'Rua Arthur Fregadolli, 272',
      bairro: 'Jardim Dias I',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 99.95,
      quartos: 3,
      banheiros: 2,
      vagas: 1,
      url: 'https://tradicaoimoveismga.com.br/imovel/69948',
    },
    {
      id: 11046,
      tipo: 'Galpão/Barracão',
      preco: 880000.0,
      endereco: 'Av. Franklin Delano Roosevelt, 982',
      bairro: 'Jd. Alvorada',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 226.0,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11046',
    },
    {
      id: 24251,
      tipo: 'Galpão/Barracão',
      preco: 895000.0,
      endereco: 'Rua Almerinda Silveira Coelho, 12407',
      bairro: 'Jardim Império do Sol',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 253.53,
      quartos: null,
      banheiros: 2,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/24251',
    },
    {
      id: 11053,
      tipo: 'Galpão/Barracão',
      preco: 900000.0,
      endereco: 'AV NAIHMA NAME, 1121',
      bairro: 'JD SÃO MIGUEL',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 287.6,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11053',
    },
    {
      id: 11040,
      tipo: 'Galpão/Barracão',
      preco: 950000.0,
      endereco: 'Av. Major Abelardo Jose da Cruz, 4185',
      bairro: 'JD GRAJAU',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 362.0,
      quartos: null,
      banheiros: 2,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11040',
    },
    {
      id: 11043,
      tipo: 'Galpão/Barracão',
      preco: 950000.0,
      endereco: 'AV PINTASSILGO, 601',
      bairro: 'JD BRASÍLIA',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 300.0,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11043',
    },
    {
      id: 11048,
      tipo: 'Galpão/Barracão',
      preco: 950000.0,
      endereco: 'AV SOPHIA RASGULAEFF, 1960',
      bairro: 'JD OASIS',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 300.0,
      quartos: null,
      banheiros: 1,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11048',
    },
    {
      id: 11049,
      tipo: 'Galpão/Barracão',
      preco: 950000.0,
      endereco: 'Avenida Dona Sophia Rasgulaeff',
      bairro: 'Jardim Oásis',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: 'BARRACAO',
      area_m2: 300.0,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11049',
    },
    {
      id: 11065,
      tipo: 'Sobrado',
      preco: 1000000.0,
      endereco: 'Rua Trinidad, 803',
      bairro: 'Vila Morangueira',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 238.0,
      quartos: 3,
      banheiros: 2,
      vagas: 4,
      url: 'https://tradicaoimoveismga.com.br/imovel/11065',
    },
    {
      id: 11199,
      tipo: 'Galpão/Barracão',
      preco: 1050000.0,
      endereco: 'Avenida São Judas Tadeu, 2547',
      bairro: 'Jardim Diamante',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 305.0,
      quartos: null,
      banheiros: 2,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11199',
    },
    {
      id: 269250,
      tipo: 'Galpão/Barracão',
      preco: 1200000.0,
      endereco: 'Avenida Pioneiro Antônio Franco de Morais, 2144',
      bairro: 'Jardim Paris VI',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 389.0,
      quartos: null,
      banheiros: 2,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/269250',
    },
    {
      id: 11067,
      tipo: 'Galpão/Barracão',
      preco: 1300000.0,
      endereco: 'Rua Mário Gealh, 1263',
      bairro: 'Residencial Ibirapuera',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 271.0,
      quartos: null,
      banheiros: 2,
      vagas: 2,
      url: 'https://tradicaoimoveismga.com.br/imovel/11067',
    },
    {
      id: 11041,
      tipo: 'Galpão/Barracão',
      preco: 1300000.0,
      endereco: 'AV DEPUTADO JOSE ALVES DOS SANTOS, 3133',
      bairro: 'JD BRASÍLIA',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 288.0,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11041',
    },
    {
      id: 11059,
      tipo: 'Galpão/Barracão',
      preco: 1500000.0,
      endereco: 'Rua Pioneiro Luiz Gavioli, 382',
      bairro: 'Jardim Paulista IV',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 508.56,
      quartos: null,
      banheiros: 2,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11059',
    },
    {
      id: 11054,
      tipo: 'Galpão/Barracão',
      preco: 1500000.0,
      endereco: 'Rua Rodolfo Cremm, 6576',
      bairro: 'Jardim Andrade',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 603.0,
      quartos: null,
      banheiros: 2,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11054',
    },
    {
      id: 47997,
      tipo: 'Sobrado',
      preco: 1950000.0,
      endereco: 'Rua Ingá, 104',
      bairro: 'Zona 05',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 439.0,
      quartos: 4,
      banheiros: 6,
      vagas: 8,
      url: 'https://tradicaoimoveismga.com.br/imovel/47997',
    },
    {
      id: 11036,
      tipo: 'Galpão/Barracão',
      preco: 2800000.0,
      endereco: 'AV MORANGUEIRA, 959',
      bairro: 'Zona 07',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 634.0,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11036',
    },
    {
      id: 132041,
      tipo: 'Galpão/Barracão',
      preco: 3000000.0,
      endereco: 'Rua Colômbia, 2248',
      bairro: 'Jardim Alvorada',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 771.0,
      quartos: null,
      banheiros: null,
      vagas: 65,
      url: 'https://tradicaoimoveismga.com.br/imovel/132041',
    },
    {
      id: 11075,
      tipo: 'Sobrado',
      preco: 3000000.0,
      endereco: 'Rua Kiri, 318',
      bairro: 'Parque da Bandeiras',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 441.0,
      quartos: 3,
      banheiros: 3,
      vagas: 5,
      url: 'https://tradicaoimoveismga.com.br/imovel/11075',
    },
    {
      id: 11061,
      tipo: 'Sobrado',
      preco: 3900000.0,
      endereco: 'ESTRADA ROMEIRINHA- GLEBA, 2413',
      bairro: 'Gleba Ribeirão Centenário',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: 'JARDINS DE MONET',
      area_m2: 524.0,
      quartos: 4,
      banheiros: 6,
      vagas: 3,
      url: 'https://tradicaoimoveismga.com.br/imovel/11061',
    },
    {
      id: 11213,
      tipo: 'Terreno',
      preco: 6000000.0,
      endereco: 'Estrada Santo Maneta, 58-A',
      bairro: '',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 72019.0,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/11213',
    },
    {
      id: 137216,
      tipo: 'Galpão/Barracão',
      preco: 20000000.0,
      endereco: 'Rua Campo Grande, 55',
      bairro: 'Setor Industrial',
      cidade: 'Sinop',
      estado: 'MT',
      condominio: null,
      area_m2: 600.0,
      quartos: null,
      banheiros: 4,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/137216',
    },
  ];

  const locacao = [
    {
      id: 328869,
      tipo: 'Apartamento',
      preco: 2300.0,
      endereco: 'Rua Guaritá, 320',
      bairro: 'Vila Bosque',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 53.0,
      quartos: 2,
      banheiros: 2,
      vagas: 1,
      url: 'https://tradicaoimoveismga.com.br/imovel/328869',
    },
    {
      id: 344255,
      tipo: 'Galpão/Barracão',
      preco: 7000.0,
      endereco: 'Avenida Pioneiro Antônio Franco de Morais, 2144',
      bairro: 'Jardim Paris VI',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 389.0,
      quartos: null,
      banheiros: 2,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/344255',
    },
    {
      id: 332706,
      tipo: 'Galpão/Barracão',
      preco: 15000.0,
      endereco: 'AV MORANGUEIRA, 959',
      bairro: 'Zona 07',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 634.0,
      quartos: null,
      banheiros: null,
      vagas: null,
      url: 'https://tradicaoimoveismga.com.br/imovel/332706',
    },
    {
      id: 297236,
      tipo: 'Galpão/Barracão',
      preco: 32000.0,
      endereco: 'Avenida Pedro Taques, 825',
      bairro: 'Vila Morangueira',
      cidade: 'Maringá',
      estado: 'PR',
      condominio: null,
      area_m2: 1380.0,
      quartos: null,
      banheiros: 8,
      vagas: 16,
      url: 'https://tradicaoimoveismga.com.br/imovel/297236',
    },
  ];

  function toRow(imovel, finalidade) {
    const slugCategoria = TIPO_CATEGORIA[imovel.tipo] || 'comercial-industrial';
    return {
      titulo: buildTitulo(imovel),
      descricao: null,
      tipo: imovel.tipo,
      finalidade,
      preco: imovel.preco,
      area_total: imovel.area_m2,
      area_construida: null,
      quartos: imovel.quartos || 0,
      suites: 0,
      banheiros: imovel.banheiros || 0,
      vagas_garagem: imovel.vagas || 0,
      endereco: imovel.endereco || null,
      bairro: imovel.bairro || null,
      cidade: imovel.cidade,
      estado: imovel.estado,
      cep: null,
      condominio: imovel.condominio || null,
      url_original: imovel.url,
      categoria_id: catMap[slugCategoria] || null,
      destaque: false,
      novo: false,
      ativo: true,
    };
  }

  const rows = [
    ...venda.map((i) => toRow(i, 'venda')),
    ...locacao.map((i) => toRow(i, 'locacao')),
  ];

  await knex('imoveis').insert(rows);
};
